name: Build_Test

on:
  - push
  - pull_request

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - ["3.10", "py310"]
          - ["3.11", "py311"]
          - ["3.12", "py312"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version[0] }}

      - name: Install tox
        run: python -m pip install tox

      - name: Build and test
        run: tox -e ${{ matrix.python-version[1] }}
